### PR TITLE
Composable Intent + Swap Layer audits

### PR DESCRIPTION
**Pull request by KristiyanFxy**

### CODE REVIEW

**Comment by djb15** [comment]
Can you rename the PDF from OtterSec please? And up to you whether you want to include the report from C4 in this PR or another one

**Comment by KristiyanFxy** [comment]
Audit names updated to reflect the dates + C4 audit added here

**Comment by djb15** [comment]
Suggested title for the OtterSec report: `2024-06-25-ottersec-composable-intents.pdf`

**Comment by KristiyanFxy** [comment]
> Suggested title for the OtterSec report: `2024-06-25-ottersec-composable-intents.pdf`

this is now done, the file has been renamed

**Review by tonyjin — APPROVED** [review]

**Pull request merged**
